---
abstract: 'Result source definitions for the Unix authentication files'
author:
  - 'Peter Flanigan, C<< <pjfl@cpan.org> >>'
build_requires:
  Module::Build: 0.4004
  version: 0.88
configure_requires:
  Module::Build: 0.4004
  version: 0.88
dynamic_config: 1
generated_by: 'Module::Build version 0.4004, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-UnixAuth
no_index:
  directory:
    - examples
    - inc
    - share
    - t
provides:
  File::UnixAuth:
    file: lib/File/UnixAuth.pm
    version: v0.18.2
  File::UnixAuth::Result:
    file: lib/File/UnixAuth/Result.pm
    version: v0.18.1
  File::UnixAuth::Storage:
    file: lib/File/UnixAuth/Storage.pm
    version: v0.18.1
recommends:
  App::cpanminus: 1.6005
requires:
  Class::Method::ModifiersX::Augment: 0.001
  File::DataClass: v0.22.0
  Lingua::EN::NameParse: 1.28
  Moo: 1.002
  namespace::sweep: 0.006
  perl: 5.010001
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=File-UnixAuth
  homepage: http://www.roxsoft.co.uk
  license: http://dev.perl.org/licenses/
version: v0.18.2
