---
abstract: 'Result source definitions for the Unix authentication files'
author:
  - 'Peter Flanigan, C<< <pjfl@cpan.org> >>'
build_requires:
  Exception::Class: 1.23
  Test::More: 0.74
  Text::Diff: 1.37
configure_requires:
  Module::Build: 0.38
  version: 0.77
dynamic_config: 1
generated_by: 'Module::Build version 0.4004, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-UnixAuth
no_index:
  directory:
    - examples
    - inc
    - t
provides:
  File::UnixAuth:
    file: lib/File/UnixAuth.pm
    version: v0.16.3
  File::UnixAuth::Result:
    file: lib/File/UnixAuth/Result.pm
    version: v0.16.3
  File::UnixAuth::Storage:
    file: lib/File/UnixAuth/Storage.pm
    version: v0.16.3
recommends:
  App::cpanminus: 1.6005
  Date::Format: 2.24
  Module::Metadata: 1.000011
  Pod::Markdown: 1.322
requires:
  File::DataClass: v0.16.0
  Lingua::EN::NameParse: 1.28
  Moose: 2.0801
  namespace::autoclean: 0.13
  perl: 5.01
  version: 0.77
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=File-UnixAuth
  homepage: http://www.roxsoft.co.uk
  license: http://dev.perl.org/licenses/
version: v0.16.3
